### ISSUE TITLE
Getting ready for presentation - Documentation

### ISSUE THREAD

**Issue by didierrc** [Arquisoft/wiq_en3b#195]
The documentation should be reviewed by all team members
and be on sync with current changes on Application.

**Comment by Raulms29** [comment]
Do you think we should delete the help that appears on each of the ssections?

**Comment by Raulms29** [comment]
# Things To Have Into Account
- Diagrams on 6.1 and 6.3 are hard to read. We should simplify them or divide them in 2 different diagrams.
- On 7.1 Quality and/or Performance Features we should remove the part that says that there are still details to be refined, since this is the final delivery.
- On 8.5.1 update ER Models for QuestionDatabase.
- Write 8.6 Operation Concepts.
- On 10.2.1 we should check if our application behaves as expected on other devices. Also a 99.9% availability
 doesn't seem very realistic. 
- We should add a section for Load Testing and Usability Testing results.
